### ISSUE TITLE
Home Assistant 0.118.3

### ISSUE THREAD

**Issue by schol478** [BasVerkooijen/cluster-lights-home-assistant#2]
Hi Bas,

Werkt dit ook op versie 0.118.3?
Handleiding heb ik gevolgd maar ik krijg geen entity te zien. Configuration.yaml geeft geen error.

Gr. Dennis

**Comment by BasVerkooijen** [comment]
Ik heb het hier draaien op 0.118.3. 

Als er geen verbinding gemaakt kan worden met de cluster verlichting bij het starten van Home Assistant, dan wordt de entity niet aangemaakt. Kun je eens kijken in Home Assistant log?

Wellicht even kijken of je de cluster lights wel kunt discoveren via bluetooth vanaf de PC/Pi?

**Comment by schol478** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/clusterlights/light.py", line 50, in setup_platform
    light = ClusterLights(device)
  File "/config/custom_components/clusterlights/light.py", line 71, in __init__
    if self._bulb.connect() is False:
  File "/config/custom_components/clusterlights/clusterlights.py", line 61, in connect
    self.device = btle.Peripheral(self.mac, addrType=btle.ADDR_TYPE_PUBLIC)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral MAC address, addr type: public

**Comment by BasVerkooijen** [comment]
Hij kan inderdaad niet verbinden met de cluster lights.

Kun je eens kijken of hij wel gediscovered wordt middels `bluetoothctl`?

`bluetoothctl`
`scan on`

`bluetoothctl` is onderdeel van de package `bluez-utils`.

Probeer eens te pairen als je cluster lights discovered:
`pair <mac-address>`

Daarna connecten:
`connect <mac-address>`

Misschien dat deze issue met pairing te maken heeft. Als je op deze manier pairet en connecten lukt, zou Home Assistant daarna ook moeten mogen connecten.

**Comment by schol478** [comment]
Op die manier kan ik netjes met de lamp verbinden echter via de integratie werkt het blijkbaar niet.

**Comment by BasVerkooijen** [comment]
Ik vind het wel gek dat in de exceptie van bluepy voor de address variabele (de %s) de string 'MAC address' invoegt. Dit had het letterlijke MAC address moeten zijn van de cluster lights in het format xx:xx:xx:xx:xx:xx. 

Weet je zeker dat de configuration.yaml goed zit? Alle indents staan goed? Kun je die hier eens plakken?

**Comment by schol478** [comment]
- platform: clusterlights
    devices:
      "24:35:CC:0F:B5:50":
       name: Kerstboom1  

Mac address had ik er namelijk van gemaakt.

**Comment by BasVerkooijen** [comment]
Ik wil een stukje test code buiten home assistant om aanleveren zodat je de integratie kunt testen vanaf de command line. De integratie bestaat namelijk uit een losse driver 'clusterlights.py' die je gewoon vanuit Python kunt gebruiken (instantiëren). Zo kan je vanaf de command line de verlichting aansturen en kunnen we onderzoeken wat er fout gaat.

Ik wil dit zelf ook even op een schoon-geïnstalleerde Raspberry Pi proberen. Ik wilde dit gister doen/maken, maar na een ```apt update``` startte de Pi niet meer op.

Ik probeer hier van de week aan toe te komen.

**Comment by schol478** [comment]
Dat is zeer nice. Bedankt alvast.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by schol478** [comment]
Bas, het lijkt te werken. Ik heb HA voorzien van de nieuwste versie en ik heb hem iets meer ram geheugen gegeven. Thanks zover!

**Comment by BasVerkooijen** [comment]
Fijn dat het werkt. Ik weet alleen niet wat er dan veranderd moet zijn wat invloed heeft op bluepy.
