### ISSUE TITLE
Other lights feature!

### ISSUE THREAD

**Issue by swbouman** [BasVerkooijen/cluster-lights-home-assistant#5]
Hoi Bas,

Ik heb ook een product uit de lights app. Dit zijn string lights. Ze worden inderdaad niet herkend door jouw integratie/component. 

Ik heb ondertussen gekeken naar de uuuid: FFF0 staat in de Bluetooth scanner. Ik heb geprobeerd om in jouw component FFF1 aan te passen maar zonder resultaat. Zou je mij een beetje op weg kunnen helpen hoe ik verder kan komen? 
evt kunnen wij dan deze code toevoegen aan de integratie en kunnen wij meer mensen blij maken. 

Hoop van je te horen. 

Mvgr

Sebastiaan

**Comment by BasVerkooijen** [comment]
Dag,

Ik had specifiek deze Homey extensie gebruikt als uitgangspunt voor hoe de karakteristieken werken: https://github.com/gruijter/com.gruijter.clusterlights/blob/master/drivers/cluster_light/device.js

Om te testen had ik deze app gebruikt: https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner&hl=nl&gl=US

Wellicht kun je ook de opdrachten van de lights app afluisteren met bluetooth HCI snoop log: https://www.mybluetoothreviews.com/what-is-bluetooth-hci-snoop-log/

Om de opdrachten te bekijken die de integratie geeft, zie clusterlights.py.

Kun je een screenshot van de karakteristieken delen?

**Comment by swbouman** [comment]
Hoi Bas,

Dank voor je antwoord, ik heb de screenshots van de karakteristieken bijgevoegd. Ik hoop dat je er iets van snapt. Ik heb het idee dat het aardig overeenkomst met de ww clusterlights. Ik duik nog even in jouw code. Voor het MAC adres neem ik aan dat die staat in het achterste gedeelte van het device ID. 

Ben erg benieuwd of we tot een oplossing komen :)

![IMG_3CD693744E20-1](https://user-images.githubusercontent.com/35607233/146761958-18615c22-0c01-491a-8ec5-74be7bd29299.jpeg)
![IMG_04A0C43FD1A4-1](https://user-images.githubusercontent.com/35607233/146761967-17876259-70b8-4fce-a761-fa3455762853.jpeg)
![IMG_103F5F79BDC5-1](https://user-images.githubusercontent.com/35607233/146761971-549f4274-c6c8-4c4e-bd4b-7ca28098f697.jpeg)
![IMG_841D0B6C8A2F-1](https://user-images.githubusercontent.com/35607233/146761973-58a28cea-8dff-4e0d-93a0-4c8d00f739b2.jpeg)
![IMG_E51DF53F0E84-1](https://user-images.githubusercontent.com/35607233/146761976-825d2e3c-a8b6-4b36-b4b4-9a955b2455ee.jpeg)

**Comment by swbouman** [comment]
Hoi Bas, 

Met de nieuwe versie werkt de clusterverlichting! Wat fijn dat je de tijd genomen hebt om naar de code te kijken en deze aan te passen. Helaas pas na de kerst ontdekt, maar voor volgend jaar werkt het :)

Sebastiaan
