### ISSUE TITLE
Connect through remote pi

### ISSUE THREAD

**Issue by phbasler** [BasVerkooijen/cluster-lights-home-assistant#6]
Hi, 

I have a feature request. Would it be possible to extract the controlling library as a seperate python module? One could then have a remote pi zero connect to the lights via BT and integrate it as an mqtt light.

**Comment by BasVerkooijen** [comment]
Hi,

The integration consists of two python files, where `light.py` contains the integration with Home Assistant and `clusterlights.py`, which is a complete independent module that you can use to control the cluster lights.

So you can use `clusterlights.py` as an independent module, instantiate clusterlights class with the MAC-address of the cluster lights and start controlling them 🙂.

**Comment by phbasler** [comment]
Alright, thanks :)
